//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdneomTST.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coffee
    {
        public int Id { get; set; }
        public int IdType { get; set; }
        public int Sucre { get; set; }
        public bool UseMug { get; set; }
    
        public virtual TypeCoffee TypeCoffee { get; set; }
    }
}
