//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdneomTST.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeCoffee
    {
        public TypeCoffee()
        {
            this.Coffee = new HashSet<Coffee>();
        }
    
        public int Id { get; set; }
        public string TypeDescription { get; set; }
    
        public virtual ICollection<Coffee> Coffee { get; set; }
    }
}
